---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-prod01
  namespace: nginx-sample
  labels:
    app: nginx-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  #clusters:
  #- name: cluster1
  clusterSelector:
    matchLabels:
      cluster-environment: prod01
  clusterReplicas: 2  #Apply to how many matched clusters, default is ALL
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-prod02
  namespace: nginx-sample
  labels:
    app: nginx-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  #clusters:
  #- name: cluster1
  clusterSelector:
    matchLabels:
      cluster-environment: prod02
  clusterReplicas: 2  #Apply to how many matched clusters, default is ALL