apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  labels:
    app: nginx-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nginx-sample
                topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: quay.io/jpacker/nginx:1.16.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: TZ
        volumeMounts:
            - mountPath: /app/index.html
              name: content-config
              subPath: index.html
      volumes:
        - name: content-config
          configMap:
            name: content-config