resources:
  - ../base
images:
  - name: quay.io/kye/nginx
    newTag: 1.16.2
configMapGenerator:
  - name: content-config
    files:
      - index.html
  - name: env-config
    literals:
      - TZ=Asia/Macau